version: '3.7'
services:
  node:
    container_name: app
    env_file:
    - .env
    build:
      context: ./
      target: development
    image: node:17.4.0-alpine3.14
    working_dir: /app
    command: yarn run start:dev
    restart: always
    networks:
      - backend
      - database
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    networks:
      - database
    volumes:
      - ./:/mongodb
    ports:
      - "27017:27017"

  mongo_seed:
    container_name: mongo_seed
    image: mongo
    links:
      - mongodb
    networks:
      - database
    volumes:
      - ./mongo-seed:/mongo-seed
    command: mongoimport --host mongodb --db metrics --collection metrics --type json --file /mongo-seed/git gigiigigigigigigmetrics.json --jsonArray

networks:
  backend:
    name: backend
    external: true
  database:
    name: database
    external: true

