swagger:
  name: "api-TrainitPlatform"
  description: ""
  license: MIT
  version: "1.0.0"
  basePath: api/v1
  outputDirectory: ./docs
  outputFormat: OpenApi_3
  entryFile:
    - ./src/Modules/infrastructure/controllers/*
    - ./src/Users/infrastructure/controller/*
    - ./src/Roles/infrastruture/controllers/*
  produces: [ controller/json ]
  securityDefinitions:
    Authenticator:
      type: apiKey
      in: header
      name: Authorization
